[profile.default]
solc-version = "0.8.18"
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 2
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config